
server {
	listen 8080;
	server_name example.com;

	location / {
		root ./www2;
		index index.html;
		allowed_methods GET;
	}
}

server {
	listen 8081;
	server_name example.com;

	location / {
		root ./www2;
		index index.html;
		allowed_methods GET;
	}
}
